---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(data.table)
library(ggplot2)
library(dplyr)
library(scales)
data_dir= "/stor/scratch/Ehrlich/MxIF/aging_thymus/human_images/human_blocks/"
```


```{r}
age_levels = c(
  "18wk", "20wk", 
  "0.003", "0.008", "0.013", "0.021", "0.025",  "0.3", "0.333", "0.833", "0.917", "1","1.166", "1.583",  "2",  "7", "8",  
  "17", "21", "22", "29", 
  "38", "54", "58", "64", "67"             
)

core_tag_levels = c(
  "A3_18wkF", "A1_20wkM", 
  "T2087-2_0.003M", "T2056-2_0.008M", "T2019-2_0.013F", "T2049-1_0.013M", "T2077-1_0.013F",
  "T2052-1_0.021M", "T2110-1_0.025M",  "T2018-3_0.3F", "T2047-1_0.333F", "T2092-4_0.833M", "T2083-1_0.917F", "T2101-1_1M",
  "T2044-2_1.166F", "T2037-3_1.583M",  
  "P49_2M",  "T2036-3_7F", "T2040-2_8F",  
  "P57_17F", "P52_21M", "T2095-2_22M", "P34_29F", 
  "P35_38F", "P42_54F", "P41-E1_58F", "P44_64F", "P36_67F"             
)

merged_ct_df = as.data.frame(fread(file.path(data_dir, "all_propagated_annotations_2026-02-09.csv"))) %>% 
  dplyr::filter(age != "2026-01-29.h5ad") %>% 
  dplyr::filter(!core_tag %in% c("T2047-1_0.333F", "T2110-1_0.025M")) %>% # stressed samples with low Ki67 stains and overall dimness
  dplyr::mutate(just_age = gsub("(F|M)$", "", age))
merged_ct_df = merged_ct_df %>% mutate(just_age = factor(just_age, levels = age_levels), 
                                       core_tag = factor(core_tag, levels= core_tag_levels))



# age_levels = c(
#   "Fetal" = "18wk", 
#   "Fetal" = "20wk", 
#   "0-8" "0.003", "0.008", "0.013", "0.013", "0.021", "0.025",  "0.3", "0.333", "0.833", "0.917", "1","1.166", "1.583",  "2",  "7", "8",  
#   "17", "21", "22", "29", 
#   "38", "54", "58", "64", "67"             
# )
```


```{r}
# Cell type frequency with age. I'm thinking a stacked bar chart here, but really I prefer faceting 
merged_ct_df %>% 
  group_by(core_tag) %>% 
  mutate(n_sample = n()) %>% 
  group_by(core_tag, ct_svm_pred) %>% 
  mutate(n_ct = n(), 
         prop_ct = n_ct / n_sample) %>% 
  dplyr::select(core_tag, sample, just_age, ct_svm_pred, prop_ct)
  


```


```{r}
# Thymocyte frequency with age. I'm thinking a stacked bar chart here, but really I prefer faceting 
thym_age = merged_ct_df %>% 
  dplyr::filter(ct_svm_pred == "Thymocyte") %>% 
  group_by(core_tag) %>% 
  mutate(n_sample = n()) %>% 
  group_by(core_tag, thym_ct_svm_pred) %>% 
  mutate(n_ct = n(), 
         prop_ct = n_ct / n_sample) %>% 
  dplyr::select(core_tag, subject_id, just_age, thym_ct_svm_pred, prop_ct, n_sample, n_ct) %>% 
  distinct() 
 
ggplot(thym_age, aes(x= core_tag, y= prop_ct)) + 
  geom_col() + 
  facet_wrap(~thym_ct_svm_pred) +
  theme(axis.text.x= element_text(angle=90))
  


```



```{r}
# Do DP_P decline with age out of thymocytes? 
dp_age = merged_ct_df %>% 
  dplyr::filter(thym_ct_svm_pred %in% c("DP_P", "DP_Q")) %>% 
  group_by(core_tag) %>% 
  mutate(n_sample = n()) %>% 
  group_by(core_tag, thym_ct_svm_pred) %>% 
  mutate(n_ct = n(), 
         prop_ct = n_ct / n_sample) %>% 
  dplyr::select(core_tag, subject_id, just_age, thym_ct_svm_pred, prop_ct, n_sample, n_ct) %>% 
  distinct() 
 
DP_P_Q_prop = ggplot(dp_age, aes(x= core_tag, y= prop_ct)) + 
  geom_col() + 
  facet_wrap(~thym_ct_svm_pred) +
  scale_x_discrete(name= "Thymus donor core ID") + 
  scale_y_continuous(name = "% of DPs", 
                     expand= expansion(mult=c(0, 0.05)), 
                     labels = scales::label_percent()) +
  theme_bw(base_size= 15) +
  theme(axis.text.x= element_text(angle=90))

ggsave(filename= file.path("/stor/work/Ehrlich/Users/John/projects/aging_thymus/data/", "DP_P_Q_prop_by_age.jpg"),
       plot= DP_P_Q_prop, 
       height= 5, 
       width = 10)


```


